### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by MichaelDBA** [dalibo/pgsql_logwatch#2]
Is this project still active?  I see no updates in a long time.

**Comment by darold** [comment]
Hi Michael,

This project is dead and hopefully reincarnated (merged) into Logwatch since v7.4.2 :-) so no more changes can be expected here. If you have some issue to report it must be done to the logwatch project or you can drop me an email I will have a look.

Cheers,

**Comment by MichaelDBA** [comment]
Thanks.
